spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/saltdb
    username: salt
    password: secret
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: postgresql
      mode: always
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
          github:
            client-id:
            client-secret: